name: armoury
version: '1.0.0'
main: me.rthom.armoury.Armoury
api-version: '1.20'

commands:
  armoury:
    description: "Armoury command"
    usage: "/armoury"
    aliases: [ arm ]
    permission: armoury.command.armoury
    permission-message: "You do not have permission to use this command"

permissions:
  armoury.command.armoury:
    default: true
  armoury.command.armoury.others:
    default: op